// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD81d7sq0_-k3oIYyehVxk4V05p0TGq89g',
    appId: '1:904909569031:web:74ce1d314d4e2be8c63ea2',
    messagingSenderId: '904909569031',
    projectId: 'rent-a-car-d06e3',
    authDomain: 'rent-a-car-d06e3.firebaseapp.com',
    storageBucket: 'rent-a-car-d06e3.firebasestorage.app',
    measurementId: 'G-S6S5X260PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxpYyTz_EBl5_O4iajDVBh1_g-c-cC97c',
    appId: '1:904909569031:android:e3845f665c5b1cd1c63ea2',
    messagingSenderId: '904909569031',
    projectId: 'rent-a-car-d06e3',
    storageBucket: 'rent-a-car-d06e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD86NomKg-UCGDegK0wG-KFT_E1SRvSMFw',
    appId: '1:904909569031:ios:54d1278f2ebbfec4c63ea2',
    messagingSenderId: '904909569031',
    projectId: 'rent-a-car-d06e3',
    storageBucket: 'rent-a-car-d06e3.firebasestorage.app',
    iosBundleId: 'com.example.rentACarApp',
  );
}
